Scholarship_Recommendation_System_tp/app1/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views



urlpatterns = [
    path("", views.index, name='home'),
    path("search_results/", views.search_results, name='search_results'),
    path("about.html", views.about, name='about'),
    path("search", views.search, name='search'),
    path("services", views.services, name='services'),
    path("contact", views.contact, name='contact'),
    path("subjects", views.subjects, name='subjects'),
    path("trainers.html", views.trainers, name='trainers'),
    path("pricing.html", views.pricing, name='pricing'),
    path("base", views.base, name='base'),
    path("registration/",views.registration, name="Registration"),
    path("login/",views.user_login, name="login"),
    path("logout/",views.user_logout, name="logout"),
    path("feedback/",views.feedback, name="feedback"),
    path("berlin-scholarship.html", views.scholarship1),
    path("canada-scholarship.html", views.scholarship2),


    path("program/add/",views.add_current_program, name="current_program"),
    path("field_of_interest/add/",views.add_field_of_interest, name="add_field_of_interest"),


    path("profile/",views.showprofile, name="userprofile"),
    path("category/subject/<str:subject>/",views.category_subjects, name="category_subjects"),
    path("category/degree/<str:degree>/",views.category_degree, name="category_degree"),

    path("profile/edit/",views.showformdata, name="userprofileedit"),
    path("setting/password/edit/",views.password_reset_settings, name="password_reset_settings"),
    path("scholarship/detail/<int:pk>/",views.scholarship_detail, name="scholarship_detail"),
    path("recommendations/",views.my_recommendations, name="my_recommendations"),
    path("history/",views.my_history, name="my_history"),
    path("scholarships.html",views.scholarshipdata, name="scholarships"),
    path("events/<id>",views.scholarshipdatadetial, name="scholarshipsdetail"),
    path("phd-list.html",views.scholarshipdegree1, name="scholarshipone"),
    path("bachelors-list.html",views.scholarshipdegree2, name="scholarshiptwo"),
    path("masters-list.html",views.scholarshipdegree3, name="scholarshipthree"),
]

Scholarship_Recommendation_System_tp/project1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Scholarship_Recommendation_System_tp/app1/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# history,program,typeofdegree

class Profile(models.Model):
    age=models.IntegerField(null=True,blank=True)
    dob=models.DateField(null=True,blank=True)
    highest_qualification=models.CharField(max_length=75,null=True,blank=True) #1
    cgpa=models.FloatField(null=True,blank=True,default=0.1)
    nationality = models.CharField(max_length=100,null=True,blank=True)
    photo = models.ImageField(default="default.jpg",upload_to="profile_pics")

    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)


    def __str__(self):
        return f"{self.user.username}'s profile"
    
    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)

        img=Image.open(self.photo.path)

        if img.height > 300 or img.width > 300:
            remain_size=(300,300)
            img.thumbnail(remain_size)
            img.save(self.photo.path)
    


class History(models.Model):
    personal_statement = models.TextField(null=True,blank=True)
    profile=models.ForeignKey(Profile, on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.personal_statement[0:50]

    
class Country(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name

class Scholarship(models.Model):
    link=models.CharField(max_length=225, null = True,blank=True)
    title=models.CharField(max_length=200, null = True,blank=True)  
    image_link=models.CharField( max_length=200, null = True,blank=True)
    tution_structure=models.CharField(max_length=30, null=True,blank=True)
    university_name=models.CharField(max_length=200, null = True,blank=True)
    degree=models.CharField(max_length=30, null = True,blank=True)
    subject=models.CharField(max_length=30, null = True,blank=True)
    eligibility=models.CharField(max_length=30, null = True,blank=True)
    country=models.CharField(max_length=30, null = True,blank=True)
    apply_date=models.CharField(max_length=200,null = True,blank=True)
    scholarship_details= models.TextField(null = True,blank=True)
    
    history = models.ManyToManyField(History,blank=True)

    def __str__(self) -> str:
        return self.title

    

class Program(models.Model):
    name=models.CharField(max_length=300,null=True,blank=True)
    profile=models.ForeignKey(Profile, on_delete=models.CASCADE,null=True,blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

class TypeOfDegree(models.Model):
    name=models.CharField(max_length=300,null=True,blank=True)
    profile=models.ForeignKey(Profile, on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.name



class FieldOfInterest(models.Model):
    name=models.CharField(max_length=300)
    profile=models.ForeignKey(Profile, on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.name


class Feedback(models.Model):
    content=models.CharField(max_length=500,null=True,blank=True)
    emoji = models.CharField(max_length=100,null=True,blank=True)
    profile=models.ForeignKey(Profile, on_delete=models.CASCADE,null=True,blank=True)
    created = models.DateTimeField(null=True,blank=True,auto_now_add=True)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ("-created",)


class Institute(models.Model):
    name=models.CharField(max_length=300,null=True,blank=True)
    city=models.CharField(max_length=30,null=True,blank=True)
    state=models.CharField(max_length=30,null=True,blank=True)
    profile=models.ForeignKey(Profile, on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.name

Scholarship_Recommendation_System_tp/app1/forms.py
from cProfile import Profile
# from curses import meta
from dataclasses import fields
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth import password_validation
from .models import *

class RegistrationForm(UserCreationForm):
    password2: forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']
        labels ={'email':'Email'}

# class ProfileInfo(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields=[]
# # age
# # dob
# # highest_Qualification
# # typeofDegree
# # cgpa
# # field_of_interest
# # personal_statement
# # user

class UserUpdateForm(forms.ModelForm):
    email=forms.EmailField()

    class Meta:
        model=User
        fields=['username','email','password']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['age','dob', 'highest_qualification', 'cgpa']

Scholarship_Recommendation_System_tp/app1/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect,redirect
from django.http import Http404
# from waitress import profile
from .models import Profile,Scholarship,History,FieldOfInterest,TypeOfDegree,Country,Feedback,Program,FieldOfInterest,Feedback
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.utils.dateparse import parse_date
from django.db.models import Q
from .utils import get_all_countries


# Create your views here.
def index(request):
    context = {}
    all_field_of_interests = FieldOfInterest.objects.all()
    all_degree_types = TypeOfDegree.objects.all()
    all_countries = Country.objects.all()
    feedbacks = Feedback.objects.all()[0:3]
    print(Feedback.objects.all())
    context['all_field_of_interests'] = all_field_of_interests
    context['all_degree_types'] = all_degree_types
    context['all_countries'] = all_countries
    context['all_feedbacks'] = feedbacks
    return render(request,"app1/index.html",context)


def search_results(request):
    all_field_of_interests = FieldOfInterest.objects.all() 
    all_degree_types = TypeOfDegree.objects.all() 
    all_countries = Country.objects.all() 

    scholarship_title = request.GET.get("scholarship_title") or None
    if scholarship_title == 'None':
        scholarship_title = None
    country = request.GET.get("country") or None
    if country == 'None':
        country = None
    field_of_interest = request.GET.get("field_of_interest") or None
    if field_of_interest == 'None':
        field_of_interest = None
    degree = request.GET.get("degree") or None
    if degree == 'None':
        degree = None
    print({'scholarship_title':scholarship_title,'country':country,'field_of_interest':field_of_interest,'degree':degree})

    page = request.GET.get('page', 1)
    if scholarship_title!=None and country==None and field_of_interest==None and degree==None:
        print("scholarship_title this is runninng")
        all_scholarships = Scholarship.objects.filter(
            title__icontains=scholarship_title
        )
    elif scholarship_title==None and country!=None and field_of_interest==None and degree==None:
        print("country this is runninng")
        all_scholarships = Scholarship.objects.filter(country__icontains=country)

    elif scholarship_title==None and country==None and field_of_interest!=None and degree==None:
        print("field_of_interest this is runninng")
        all_scholarships = Scholarship.objects.filter(subject__icontains=field_of_interest)

    elif scholarship_title==None and country==None and field_of_interest==None and degree!=None:
        print("degree this is runninng")
        all_scholarships = Scholarship.objects.filter(degree__icontains=degree)

    elif scholarship_title!=None and country!=None and field_of_interest==None and degree==None:
        print("scholarship_title country this is runninng")
        all_scholarships = Scholarship.objects.filter(title__icontains=scholarship_title,country__icontains=country)
    
    elif scholarship_title!=None and country==None and field_of_interest!=None and degree==None:
        print("scholarship_title field_of_interest this is runninng")

        all_scholarships = Scholarship.objects.filter(title__icontains=scholarship_title,subject__icontains=field_of_interest)
    
    elif scholarship_title!=None and country==None and field_of_interest==None and degree!=None:
        print("scholarship_title degree this is runninng")

        all_scholarships = Scholarship.objects.filter(title__icontains=scholarship_title,degree__icontains=degree)
    
    elif scholarship_title==None and country!=None and field_of_interest!=None and degree==None:
        print("country field_of_interest this is runninng")
        all_scholarships = Scholarship.objects.filter(country__icontains=country,subject__icontains=field_of_interest)
    
    elif scholarship_title==None and country!=None and field_of_interest==None and degree!=None:
        print("country degree this is runninng")

        all_scholarships = Scholarship.objects.filter(country__icontains=country,degree__icontains=degree)

    elif scholarship_title==None and country==None and field_of_interest!=None and degree!=None:
        print("field_of_interest degree this is runninng")
        all_scholarships = Scholarship.objects.filter(subject__icontains=field_of_interest,degree__icontains=degree)
        
    
    elif scholarship_title!=None and country!=None and field_of_interest!=None and degree==None:
        print("scholarship_title country field_of_interest this is runninng")
        all_scholarships = Scholarship.objects.filter(title__icontains=scholarship_title,country__icontains=country,subject__icontains=field_of_interest)
    
    elif scholarship_title!=None and country!=None and field_of_interest==None and degree!=None:
        print("scholarship_title country degree this is runninng")
        all_scholarships = Scholarship.objects.filter(title__icontains=scholarship_title,country__icontains=country,degree__icontains=degree)
  
    
    elif scholarship_title!=None and country==None and field_of_interest!=None and degree!=None:
        print("scholarship_title field_of_interest degree this is runninng")
        all_scholarships = Scholarship.objects.filter(title__icontains=scholarship_title,subject__icontains=field_of_interest,degree__icontains=degree)

    elif scholarship_title==None and country!=None and field_of_interest!=None and degree!=None:
        print("field_of_interest country degree this is runninng")
        all_scholarships = Scholarship.objects.filter(country__icontains=country,degree__icontains=degree,subject__icontains=field_of_interest)

    elif scholarship_title!=None and country!=None and field_of_interest!=None and degree!=None:
        print("scholarship_title country field_of_interest degree this is runninng")
        all_scholarships = Scholarship.objects.filter(title__icontains=scholarship_title,country__icontains=country,subject__icontains=field_of_interest,degree__icontains=degree)
    else:
        return redirect("home")

    paginator = Paginator(all_scholarships, 10)
    try:
        scholarships = paginator.page(page)
    except not isinstance(page,int):
        scholarships = paginator.page(1)
    except:
        scholarships = paginator.page(paginator.num_pages)
    print(scholarships)
    context = {
        'scholarships':scholarships,
        'scholarship_title':scholarship_title,
        'country':country,
        'field_of_interest':field_of_interest,
        'degree':degree,
        'number_of_scholarships':len(all_scholarships),
    }
    context['all_field_of_interests'] = all_field_of_interests
    context['all_degree_types'] = all_degree_types
    context['all_countries'] = all_countries
    return render(request,"app1/scholarship_results.html",context)



def base(request):
    return render(request,"app1/base.html")

def subjects(request):
    context = {}
    all_subjects = FieldOfInterest.objects.all()
    mydata = [all_subjects[i:i + 15] for i in range(0, len(all_subjects), 15)]
    context['all_subjects'] = mydata
    return render(request,"app1/subjects.html",context)

def category_subjects(request,subject):
    context = {}
    all_scholarships = Scholarship.objects.filter(subject__icontains=subject)
    page = request.GET.get('page', 1)
    paginator = Paginator(all_scholarships, 10)
    try:
        scholarships = paginator.page(page)
    except not isinstance(page,int):
        scholarships = paginator.page(1)
    except:
        scholarships = paginator.page(paginator.num_pages)
    context['scholarships']= scholarships
    context['number_of_scholarships']=len(all_scholarships)
    return render(request,'app1/category_subjects.html',context)

def trainers(request):
    return render(request,"app1/trainers.html")


def category_degree(request,degree):
    context = {}
    all_scholarships = Scholarship.objects.filter(degree__icontains=degree)
    page = request.GET.get('page', 1)
    paginator = Paginator(all_scholarships, 10)
    try:
        scholarships = paginator.page(page)
    except not isinstance(page,int):
        scholarships = paginator.page(1)
    except:
        scholarships = paginator.page(paginator.num_pages)
    context['scholarships']= scholarships
    context['number_of_scholarships']=len(all_scholarships)
    return render(request,'app1/category_degree.html',context)

def pricing(request):
    return render(request,"app1/pricing.html")

def events(request):
    return render(request,"app1/events.html")

def scholarship1(request):
    return render(request, "app1/berlin-scholarship.html")
    
def scholarship2(request):
    return render(request, "app1/canada-scholarship.html")

def about(request):
    return render(request,"app1/about.html")
    #return HttpResponse("this is about page")

def services(request):
    return HttpResponse("this is services page")

def contact(request):
    return HttpResponse("this is contact page")

#RegistrationView Function
def registration(request):
    if request.method == 'POST':
        u_name = request.POST.get('username')
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password1']
        confirm_password = request.POST['password2']
        try:
            user = User.objects.get(email=email)
            if user:
                messages.error(request, 'The email you entered already exists.')
                return redirect("Registration")
        except:
            if password == confirm_password:

Scholarship_Recommendation_System_tp/app1/templates/app1/bachelors-list.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">

{% block body %}
{% load static%}

  <main id="main" data-aos="fade-in">

    <!-- ======= Breadcrumbs ======= -->
     <div class="breadcrumbs">
      <div class="container">
        <h2>Bachelors Scholarships</h2>
        {% comment %} <p>​​​​​There are many scholarships available at postgraduate and doctorate levels to help academically gifted students and faculty. </p> {% endcomment %}
      </div>
    </div><!-- End Breadcrumbs --> 

    <!-- ======= Trainers Section ======= -->
    <section id="trainers" class="trainers">
      <div class="container" data-aos="fade-up">

        <div class="row" data-aos="zoom-in" data-aos-delay="100">
          <div class="col-lg-6 col-md-6 d-flex align-items-stretch">
            <div class="member">
              {% comment %} <img src="{% static 'assets/img/trainers/phd.jpg'%}" class="img-fluid" alt=""> {% endcomment %}
              
            </div>
          </div>

        </div>
        {% comment %} <ul>
          {% for phd in scholarshipsone %}
            
           <li> {{phd}} </li>
          
          {% endfor %}
        </ul>  {% endcomment %}

        <h1>List of Bachelors Scholarships:</h1>
        <ul>
          {% for scholarbachelors in scholarshiptwo %}
               <li>   {{scholarbachelors}}  </li> 
          {% endfor %}
        </ul> 
        {% comment %} 
        <h4>
        <ul><a href="">
            Rhodes Scholarships at Oxford University for International Students
        </a> </ul>
        <ul><a href="">
            Italian Government Scholarships for Foreign Students
        </a></ul>
        <ul><a href="">
            Rotary Foundation Global Scholarship Grants for Development
        </a></ul>
        <ul><a href="">
            The Global Excellence Scholarship at the University of Western Australia
        </a></ul>
        <ul><a href="">
            FINCAD Women in Finance Scholarship
        </a></ul>
        <ul><a href="">
            Australia Awards Scholarships
        </a></ul>
        <ul><a href="">
            JFUNU Scholarships for PhD in Sustainability Science
        </a></ul>
        <ul><a href="">
            Heinrich Boll Scholarships in Germany for International Students
        </a></ul>
        <ul><a href="">
            Fulbright Foreign Student Program in USA
        </a></ul>
    </h4> {% endcomment %}
        {% comment %} <ul><a href="">
            Heinrich Boll Scholarships in Germany for International Students
        </a></ul>
        <ul><a href="">
            Heinrich Boll Scholarships in Germany for International Students
        </a></ul> {% endcomment %}
         
     
 
      </div>
    </section><!-- End Trainers Section -->

  </main><!-- End #main -->

  
{% endblock %}
</html>

Scholarship_Recommendation_System_tp/app1/templates/app1/profile_edit.html
{% extends 'base.html' %}
{% if user.is_authenticated %}
{% load static %}

{% block custom_css_links %}
<link href="{% static 'assets/css/profile_style.css' %}" rel="stylesheet">
{% endblock custom_css_links %}

{% block body %}
<div class="main-content">

  <!-- Header -->
  <div class="header d-flex align-items-center" style="min-height: 180px;">
    <span class="mask opacity-8"></span>
  </div>
  <!-- Page content -->
  <div class="container-fluid mt-6">
    <div class="row">
      <div class="col-xl-3 order-xl-1 mb-5 mb-xl-0">
        <div class="card card-profile shadow">
          <div class="row justify-content-center">
            <div class="col-lg-3 order-lg-2">
              <div class="card-profile-image">
                <a href="#">
                  <img src="{{user.profile.photo.url}}" class="rounded-circle" width="100px" height="100px"
                    style="object-fit: cover;"> </a>
              </div>
            </div>
          </div>
          <div class="card-body pt-0 pt-md-4">

            <div class="mt-5 pt-5">
              <div class="text-center">
                <h2 class="text-center pb-3">
                  {{ request.user.username.capitalize }}
                </h2>

              </div>

              <hr class="my-4">
              <div class="row">
                <a href="{% url 'userprofile' %}" class="col-md-12 py-2"><i class="bi bi-person-fill mx-2"></i>My
                  Profile</a>
                <a href="{% url 'my_recommendations' %}" class="col-md-12 py-2"><i class="bi bi-file-text mx-2"></i>My
                  Recommmendations</a>
                <a href="{% url 'feedback' %}" class="col-md-12 py-2"><i class="bi bi-file-text mx-2"></i>Feedback</a>
                <a href="{% url 'my_history' %}" class="col-md-12 py-2"><i class="bi bi-file-text mx-2"></i>History</a>
                <a href="{% url 'logout' %}" class="col-md-12 py-2"><i class="bi bi-arrow-up-right mx-2"></i>Logout</a>
              </div>

            </div>
          </div>
        </div>
      </div>

      <div class="col-xl-9 order-xl-2">
        <div class="card bg-secondary shadow">
          <div class="card-header bg-white border-0">
            <div class="row align-items-center">
              <div class="col-8">
                <h3 class="mb-0">My account</h3>
              </div>

            </div>
          </div>
          <div class="card-body">
            <!-- Form -->
            {{p_form.non_field_errors}}
            <form action="" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              {% if messages %}
              {% for message in messages %}
              <div class="alert alert-{{message.tags}}"
                style="background-color: #5E72E4;padding: 15px 20px;margin-bottom: 20px;color: white;border-radius: 7px;">
                {{message}}
              </div>

              {% endfor %}
              {% endif %}
              {% block content %}{% endblock %}
              <h6 class="heading-small text-muted mb-4">User information</h6>
              <div class="pl-lg-4">
                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group focused">
                      <label class="form-control-label" for="id_First_Name">First name</label>
                      <input type="text" name="first_name" maxlength="30" id="id_First_Name"
                        class="form-control form-control-alternative" value="{{user.first_name}}">

                    </div>
                  </div>
                  <div class="col-lg-6">
                    <div class="form-group focused">
                      <label class="form-control-label" for="id_Last_Name">Last name</label>

                      <input type="text" name="last_name" maxlength="30" id="id_Last_Name"
                        class="form-control form-control-alternative" value="{{user.last_name}}">

                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <!-- <label class="form-control-label" for="input-email">Email address</label> -->
                      <label class="form-control-label" for="id_Email">Email</label>
                      <input type="email" name="email" class="form-control form-control-alternative" maxlength="50"
                        id="id_Email" value="{{user.email}}">
                      <input type="hidden" id="input-email-hidden" class="form-control form-control-alternative"
                        name="hidden_user_email" value="{{user.email}}">
                    </div>
                  </div>
                  <div class="col-lg-6">
                    <div class="form-group">
                      <!-- <label class="form-control-label" for="input-email">Email address</label> -->
                      <label class="form-control-label" for="id_photo">Profile Photo</label>
                      <input type="file" name="photo" class="form-control form-control-alternative" maxlength="50"
                        id="id_photo" value="{{user.profile.photo.url}}" accept="image/jpeg">
                    </div>
                  </div>
                </div>


                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <!-- <label class="form-control-label" for="input-email">Email address</label> -->
                      <label class="form-control-label" for="highest_qualification">Highest Qualification</label>
                      {% if user.profile.highest_qualification %}
                      <input type="text" name="highest_qualification" class="form-control form-control-alternative"
                        maxlength="50" id="highest_qualification" value="{{user.profile.highest_qualification}}">
                      {% else %}
                      <input type="text" name="highest_qualification" class="form-control form-control-alternative"
                        maxlength="50" id="highest_qualification" value="">
                      {% endif %}

                    </div>
                  </div>
                  <div class="col-lg-6">
                    <div class="form-group">
                      <!-- <label class="form-control-label" for="input-email">Email address</label> -->
                      <label class="form-control-label" for="nationality">Nationality</label>
                      {% if user.profile.nationality %}
                      <input type="text" name="nationality" class="form-control form-control-alternative" maxlength="50"
                        id="nationality" value="{{user.profile.nationality}}">
                      {% else %}
                      <input type="text" name="nationality" class="form-control form-control-alternative" maxlength="50"
                        id="nationality" value="">
                      {% endif %}

                    </div>
                  </div>
                </div>

              </div>
              <hr class="my-4">
              <!-- Address -->
              <h6 class="heading-small text-muted mb-4">Academic Information</h6>
              <div class="pl-lg-4">
                <div class="row">
                  <div class="col-lg-4">
                    <div class="form-group">
                      <label for="age" class="form-control-label">Age</label>
                      <input type="number" name="age" maxlength="300" id="age"
                        class="form-control form-control-alternative" value="{{user.profile.age}}">
                    </div>
                  </div>
                  <div class="col-lg-4">
                    <div class="form-group">
                      <label for="dob" class="form-control-label">DOB</label>
                      <input type="date" name="dob" maxlength="300" id="dob"
                        class="form-control form-control-alternative" value="{{user.profile.dob| date:'Y-m-d'}}">
                    </div>
                  </div>
                  <div class="col-lg-4">
                    {% if user.profile.cgpa %}
                    <div class="form-group">
                      <label for="cgpa" class="form-control-label">CGPA</label>
                      <input type="text" name="cgpa" maxlength="300" id="cgpa"
                        class="form-control form-control-alternative" value="{{user.profile.cgpa}}">
                    </div>
                    {% else %}
                    <div class="form-group">
                      <label for="cgpa" class="form-control-label">CGPA</label>
                      <input type="text" name="cgpa" maxlength="300" id="cgpa"
                        class="form-control form-control-alternative">
                    </div>
                    {% endif %}
                  </div>
                </div>
              </div>
              <hr class="my-4">


              <input type="submit" value="Save" class="btn btn-primary" style="background-color: #31526B; color:white;">
              <a href="{% url 'userprofile' %}">
                <button class="btn btn-secondary" id="sign-in-btn">Cancel</button>
              </a>

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




<script>
  function openPage() {
    var x = document.getElementById("search").value;

    if (x === "berlin" || x === "Berlin") {
      window.open("/berlin-scholarship.html");
    }
    if (x === "canada" || x === "Canada") {
      window.open("/canada-scholarship.html");
    }
    if (x === "phd" || x === "PhD" || x === "PHD") {
      window.open("/phd-list.html");
    }
  }


</script>
{% endblock %}



{% else %}
<h1> You are not logged in </h1>


{% endif %}